import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { FeedbackProvider } from '../../components/FeedbackProvider';
import { HttpError } from '../../api/client';
import { RiesgoDetailPage } from './RiesgoDetailPage';

const api = vi.hoisted(() => ({ obtenerRiesgo: vi.fn(), listarSeguimientosRiesgo: vi.fn(), listarCompromisosRiesgo: vi.fn(), historialRiesgo: vi.fn(), crearSeguimientoRiesgo: vi.fn(), crearCompromisoRiesgo: vi.fn() }));
vi.mock('../../api/riesgosTrabajo', () => ({ ...api }));
vi.mock('../formularios/ContextFormsPanel', () => ({ ContextFormsPanel: ({ riesgoId }: { riesgoId?: string }) => <div>Formularios Riesgos {riesgoId}</div> }));
vi.mock('../documentos/DocumentosPanel', () => ({ DocumentosPanel: ({ riesgoId }: { riesgoId?: string }) => <div>Documentos Riesgos {riesgoId}</div> }));

const risk = { id_caso: 'risk-1', codigo_caso: 'RIE-001', tipo_caso: 'RIESGOS_TRABAJO', persona_id: 'p1', persona: 'Ana', cedula: '001', area: 'Operaciones', fecha_apertura: '2026-09-15', responsable: 'Rosa', estado_caso: 'ABIERTO', prioridad: null, resultado: 'Evaluación', resumen: 'Evaluación', ultimo_seguimiento: null, fecha_creacion: '2026-09-15', fecha_actualizacion: '2026-09-15', fecha_cierre: null, motivo_cierre: null, registrado_por: 'admin@example.com', version: 1 };
function page() { return render(<MemoryRouter initialEntries={['/trabajo-social/departamento-medico/riesgos/risk-1']}><FeedbackProvider><Routes><Route path="/trabajo-social/departamento-medico/riesgos/:id" element={<RiesgoDetailPage />} /></Routes></FeedbackProvider></MemoryRouter>); }
beforeEach(() => { vi.clearAllMocks(); api.obtenerRiesgo.mockResolvedValue(risk); api.listarSeguimientosRiesgo.mockResolvedValue([{ id_seguimiento: 's1', fecha: '2026-09-16', responsable: 'Rosa', descripcion: 'Contacto', resultado: null, proxima_accion: null, fecha_proxima_accion: null, estado: 'ABIERTO', creado_por: 'admin@example.com' }]); api.listarCompromisosRiesgo.mockResolvedValue([{ id_compromiso: 'c1', responsable: 'Rosa', descripcion: 'Informe', fecha_limite: '2026-10-01', estado: 'PENDIENTE', observacion: null, creado_por: 'admin@example.com' }]); api.historialRiesgo.mockResolvedValue([{ campo: 'estado', accion: 'CREATE', valor_anterior: null, valor_nuevo: 'ABIERTO', usuario: 'admin@example.com', fecha_hora: '2026-09-15', motivo: null }]); });

describe('RiesgoDetailPage', () => {
  it('renderiza resumen, Persona, responsable y las seis secciones contextuales', async () => { page(); expect(screen.getByText('Cargando Riesgo…')).toBeInTheDocument(); await screen.findByRole('heading', { name: 'RIE-001' }); expect(screen.getByText('Ana')).toBeInTheDocument(); expect(screen.getByText('Rosa')).toBeInTheDocument(); expect(screen.getAllByRole('tab')).toHaveLength(6); });
  it('navega Seguimientos, Compromisos, Formularios, Documentos e Historial', async () => { page(); const user = userEvent.setup(); await screen.findByRole('heading', { name: 'RIE-001' }); await user.click(screen.getByRole('tab', { name: /Seguimientos/ })); expect(screen.getByText('Contacto')).toBeInTheDocument(); await user.click(screen.getByRole('tab', { name: /Compromisos/ })); expect(screen.getByText('Informe')).toBeInTheDocument(); await user.click(screen.getByRole('tab', { name: 'Formularios' })); expect(screen.getByText('Formularios Riesgos risk-1')).toBeInTheDocument(); await user.click(screen.getByRole('tab', { name: 'Documentos' })); expect(screen.getByText('Documentos Riesgos risk-1')).toBeInTheDocument(); await user.click(screen.getByRole('tab', { name: 'Historial' })); expect(screen.getByText(/CREATE/)).toBeInTheDocument(); });
  it('crea seguimiento y compromiso con el id contextual y evita doble submit', async () => { api.crearSeguimientoRiesgo.mockImplementation(() => new Promise(() => undefined)); page(); const user = userEvent.setup(); await screen.findByRole('heading', { name: 'RIE-001' }); await user.click(screen.getByRole('tab', { name: /Seguimientos/ })); await user.type(screen.getByLabelText('Contenido *'), 'Nuevo seguimiento'); await user.click(screen.getByRole('button', { name: 'Guardar seguimiento' })); expect(api.crearSeguimientoRiesgo).toHaveBeenCalledWith('risk-1', expect.objectContaining({ descripcion: 'Nuevo seguimiento' })); expect(screen.getByRole('button', { name: 'Guardando…' })).toBeDisabled(); });
  it('muestra estados vacíos, error, 401 y 403 del detalle', async () => { api.listarSeguimientosRiesgo.mockResolvedValue([]); api.listarCompromisosRiesgo.mockResolvedValue([]); api.historialRiesgo.mockResolvedValue([]); page(); const user = userEvent.setup(); await screen.findByRole('heading', { name: 'RIE-001' }); await user.click(screen.getByRole('tab', { name: /Seguimientos/ })); expect(screen.getByText('Aún no hay seguimientos.')).toBeInTheDocument(); await user.click(screen.getByRole('tab', { name: /Compromisos/ })); expect(screen.getByText('Aún no hay compromisos.')).toBeInTheDocument(); await user.click(screen.getByRole('tab', { name: 'Historial' })); expect(screen.getByText('Sin eventos registrados.')).toBeInTheDocument(); });
  it('presenta 401 y 403 si la carga contextual es rechazada', async () => { api.obtenerRiesgo.mockRejectedValueOnce(new HttpError(401, { ok: false, code: 'SESSION_REQUIRED', message: 'Inicie sesión.', correlationId: '' })); page(); expect(await screen.findByText('Inicie sesión.')).toBeInTheDocument(); api.obtenerRiesgo.mockRejectedValueOnce(new HttpError(403, { ok: false, code: 'FORBIDDEN', message: 'Sin permiso.', correlationId: '' })); page(); expect(await screen.findByText('Sin permiso.')).toBeInTheDocument(); });
});
