import { useEffect, useState, type FormEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { HttpError } from '../../api/client';
import { crearCompromisoRiesgo, crearSeguimientoRiesgo, historialRiesgo, listarCompromisosRiesgo, listarSeguimientosRiesgo, obtenerRiesgo, type RiesgoCompromiso, type RiesgoHistorial, type RiesgoSeguimiento, type RiesgoTrabajo } from '../../api/riesgosTrabajo';
import { DocumentosPanel } from '../documentos/DocumentosPanel';
import { ContextFormsPanel } from '../formularios/ContextFormsPanel';
import { useFeedback } from '../../components/FeedbackProvider';

type Tab = 'resumen' | 'seguimientos' | 'compromisos' | 'formularios' | 'documentos' | 'historial';
const today = () => new Date().toISOString().slice(0, 10);
const text = (value: string | null | undefined) => value || '—';
const errorText = (error: unknown, fallback: string) => error instanceof HttpError ? error.message : fallback;

export function RiesgoDetailPage() {
  const { id = '' } = useParams(); const { notify } = useFeedback(); const [tab, setTab] = useState<Tab>('resumen'); const [riesgo, setRiesgo] = useState<RiesgoTrabajo | null>(null); const [seguimientos, setSeguimientos] = useState<RiesgoSeguimiento[]>([]); const [compromisos, setCompromisos] = useState<RiesgoCompromiso[]>([]); const [historial, setHistorial] = useState<RiesgoHistorial[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [sending, setSending] = useState(false);
  async function load() { setLoading(true); setError(null); try { const [item, follows, commitments, events] = await Promise.all([obtenerRiesgo(id), listarSeguimientosRiesgo(id), listarCompromisosRiesgo(id), historialRiesgo(id)]); setRiesgo(item); setSeguimientos(follows); setCompromisos(commitments); setHistorial(events); } catch (caught) { setError(errorText(caught, 'No fue posible cargar el Riesgo.')); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [id]);
  async function follow(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (sending) return; const data = new FormData(event.currentTarget); setSending(true); try { await crearSeguimientoRiesgo(id, { fecha: String(data.get('fecha')), descripcion: String(data.get('descripcion')), resultado: String(data.get('resultado') || '') || undefined, proxima_accion: String(data.get('proxima_accion') || '') || undefined, fecha_proxima_accion: String(data.get('fecha_proxima_accion') || '') || undefined, estado: 'ABIERTO' }); event.currentTarget.reset(); await load(); notify('Seguimiento registrado correctamente.'); } catch (caught) { setError(errorText(caught, 'No fue posible guardar el seguimiento.')); } finally { setSending(false); } }
  async function commitment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (sending) return; const data = new FormData(event.currentTarget); setSending(true); try { await crearCompromisoRiesgo(id, { responsable: String(data.get('responsable') || '') || undefined, descripcion: String(data.get('descripcion')), fecha_limite: String(data.get('fecha_limite') || '') || undefined, estado: 'PENDIENTE', observacion: String(data.get('observacion') || '') || undefined }); event.currentTarget.reset(); await load(); notify('Compromiso registrado correctamente.'); } catch (caught) { setError(errorText(caught, 'No fue posible guardar el compromiso.')); } finally { setSending(false); } }
  if (loading) return <p className="loading-message">Cargando Riesgo…</p>;
  if (!riesgo) return <p className="form-error">{error ?? 'Riesgo no encontrado.'}</p>;
  const labels: [Tab, string][] = [['resumen', 'Resumen'], ['seguimientos', `Seguimientos (${seguimientos.length})`], ['compromisos', `Compromisos (${compromisos.length})`], ['formularios', 'Formularios'], ['documentos', 'Documentos'], ['historial', 'Historial']];
  return <div className="detail-page"><Link className="back-link" to="/trabajo-social/departamento-medico/riesgos">← Volver a Riesgos</Link><section className="panel"><p className="eyebrow">Riesgo de trabajo</p><h2>{riesgo.codigo_caso}</h2>{error && <p className="form-error" role="alert">{error}</p>}</section><div className="tabs" role="tablist" aria-label="Secciones del Riesgo">{labels.map(([value, label]) => <button key={value} type="button" role="tab" aria-selected={tab === value} onClick={() => setTab(value)}>{label}</button>)}</div>
    {tab === 'resumen' && <section className="panel tab-panel"><h2>Resumen</h2><dl className="field-list">{Object.entries({ ID: riesgo.id_caso, Código: riesgo.codigo_caso, Persona: riesgo.persona, Cédula: riesgo.cedula, Área: riesgo.area, Descripción: riesgo.resultado ?? riesgo.resumen, Estado: riesgo.estado_caso, Responsable: riesgo.responsable, Autor: riesgo.registrado_por, 'Fecha de apertura': riesgo.fecha_apertura, 'Fecha de creación': riesgo.fecha_creacion, 'Última actualización': riesgo.fecha_actualizacion, 'Fecha de cierre': riesgo.fecha_cierre, 'Motivo de cierre': riesgo.motivo_cierre, Versión: String(riesgo.version) }).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{text(value)}</dd></div>)}</dl></section>}
    {tab === 'seguimientos' && <section className="panel tab-panel"><h2>Seguimientos</h2>{riesgo.estado_caso !== 'CERRADO' && <form className="form-grid" onSubmit={follow}><label>Fecha<input name="fecha" type="date" defaultValue={today()} required /></label><label className="full-width">Contenido *<textarea name="descripcion" required /></label><label>Resultado<input name="resultado" /></label><label>Próxima acción<input name="proxima_accion" /></label><label>Fecha próxima<input name="fecha_proxima_accion" type="date" /></label><div className="full-width"><button disabled={sending}>{sending ? 'Guardando…' : 'Guardar seguimiento'}</button></div></form>}{seguimientos.length ? <ul className="history-list">{seguimientos.map((item) => <li key={item.id_seguimiento}><strong>{item.descripcion}</strong><small>{text(item.fecha)} · Autor: {text(item.creado_por)} · Responsable: {text(item.responsable)}</small></li>)}</ul> : <p className="footnote">Aún no hay seguimientos.</p>}</section>}
    {tab === 'compromisos' && <section className="panel tab-panel"><h2>Compromisos</h2>{riesgo.estado_caso !== 'CERRADO' && <form className="form-grid" onSubmit={commitment}><label>Responsable<input name="responsable" /></label><label>Fecha límite<input name="fecha_limite" type="date" /></label><label className="full-width">Compromiso *<textarea name="descripcion" required /></label><label className="full-width">Observación<textarea name="observacion" /></label><div className="full-width"><button disabled={sending}>{sending ? 'Guardando…' : 'Guardar compromiso'}</button></div></form>}{compromisos.length ? <ul className="history-list">{compromisos.map((item) => <li key={item.id_compromiso}><strong>{item.descripcion}</strong><small>{text(item.estado)} · {text(item.fecha_limite)} · Responsable: {text(item.responsable)} · Autor: {text(item.creado_por)}</small></li>)}</ul> : <p className="footnote">Aún no hay compromisos.</p>}</section>}
    {tab === 'formularios' && <div className="tab-panel"><ContextFormsPanel contextType="CASOS" contextId={id} riesgoId={id} /></div>}
    {tab === 'documentos' && <div className="tab-panel"><DocumentosPanel tipoRegistro="CASOS" idRegistro={id} riesgoId={id} /></div>}
    {tab === 'historial' && <section className="panel tab-panel"><h2>Historial</h2>{historial.length ? <ul className="history-list">{historial.map((event, index) => <li key={`${event.fecha_hora}-${index}`}><strong>{event.accion} · {event.campo}</strong><small>{event.fecha_hora} · {event.usuario}{event.motivo ? ` · ${event.motivo}` : ''}</small></li>)}</ul> : <p className="footnote">Sin eventos registrados.</p>}</section>}
  </div>;
}
