import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it, vi } from 'vitest';
import { MemoryRouter } from 'react-router-dom';
import { HttpError } from '../../api/client';
import { ContextualFormsPage, CONTEXTUAL_FORM_BRANCHES, type ContextualFormsConfig } from './ContextualFormsPage';

const api = vi.hoisted(() => ({ listDestinationTree: vi.fn(), listFormDefinitions: vi.fn(), listDestinationResponses: vi.fn() }));
vi.mock('../../api/formBuilder', async () => ({ ...await vi.importActual<typeof import('../../api/formBuilder')>('../../api/formBuilder'), ...api }));
vi.mock('../../app/AuthContext', () => ({ useAuth: () => ({ usuario: { permisos: { FORMULARIOS: { edit: true } } } }) }));
const node = (id: string, codigo: string, nombre: string, hijos: unknown[] = []) => ({ id_destino: id, codigo, nombre, nivel: hijos.length ? 'PROCESO' as const : 'SUBPROCESO' as const, padre_id_destino: null, activo: true, orden: 1, hijos });
const tree = [{ ...node('ts', 'TRABAJO_SOCIAL', 'Trabajo Social', [node('activities', 'ACTIVIDADES', 'Actividades', [node('general', 'GENERAL', 'General')]), node('medical', 'DEPARTAMENTO_MEDICO', 'Departamento Médico', [node('risk', 'RIESGOS_TRABAJO', 'Riesgos de trabajo'), node('absence', 'AUSENTISMOS', 'Ausentismos'), node('accident', 'ACCIDENTES', 'Accidentes')]), node('production', 'PRODUCCION', 'Producción', [node('rounds', 'RECORRIDOS', 'Recorridos'), node('news', 'NOVEDADES_PLANTA', 'Novedades de planta'), node('attention', 'ATENCIONES', 'Atenciones')]), node('office', 'OFICINA', 'Oficina', [node('benefits', 'BENEFICIOS', 'Beneficios'), node('office-attention', 'ATENCIONES', 'Atenciones'), node('loans', 'PRESTAMOS', 'Préstamos'), node('insurance', 'SEGURO', 'Seguro')])]) }];
const form = (id: string, destinations: string[]) => ({ id_formulario: id, nombre: id, descripcion: null, responsable: null, estado: 'PUBLICADO' as const, fecha_publicacion: null, fecha_actualizacion: null, actualizado_por: null, permite_multiples_respuestas: false, version_publicada: 1, version: 1, activo: true, eliminado: false, destinos: [], destinos_jerarquicos: destinations, total_preguntas: 1, total_respuestas: 0, secciones: [], preguntas: [], reglas: [] });
function renderPage(config: ContextualFormsConfig = CONTEXTUAL_FORM_BRANCHES.medical) { api.listDestinationTree.mockResolvedValue(tree); api.listFormDefinitions.mockResolvedValue([form('Múltiple', ['absence', 'accident']), form('Producción', ['rounds']), form('Histórico', [])]); api.listDestinationResponses.mockResolvedValue([]); render(<MemoryRouter><ContextualFormsPage config={config} /></MemoryRouter>); }
describe('ContextualFormsPage', () => {
  it('muestra una vez la unión explícita de subprocesos de la rama', async () => { renderPage(); expect(await screen.findByText('Múltiple')).toBeInTheDocument(); expect(screen.queryByText('Producción')).not.toBeInTheDocument(); expect(screen.getAllByText('Múltiple')).toHaveLength(1); });
  it('filtra por subproceso sin inferir destinos de otras ramas', async () => { renderPage(); const user = userEvent.setup(); await screen.findByText('Múltiple'); await user.selectOptions(screen.getByLabelText('Subproceso'), 'AUSENTISMOS'); expect(screen.getByText('Múltiple')).toBeInTheDocument(); await user.selectOptions(screen.getByLabelText('Subproceso'), 'ACCIDENTES'); expect(screen.getByText('Múltiple')).toBeInTheDocument(); });
  it('muestra el estado vacío cuando no hay asignaciones jerárquicas de la rama', async () => { api.listDestinationTree.mockResolvedValue(tree); api.listFormDefinitions.mockResolvedValue([form('Histórico', [])]); render(<MemoryRouter><ContextualFormsPage config={CONTEXTUAL_FORM_BRANCHES.medical} /></MemoryRouter>); expect(await screen.findByText('No hay formularios asignados a esta rama.')).toBeInTheDocument(); });
  it('usa el mismo componente para Producción y no incluye otras ramas', async () => { renderPage(CONTEXTUAL_FORM_BRANCHES.production); expect(await screen.findByText('Producción')).toBeInTheDocument(); expect(screen.queryByText('Múltiple')).not.toBeInTheDocument(); });
  it('comunica errores de autorización del backend', async () => { api.listDestinationTree.mockRejectedValue(new HttpError(403, { ok: false, code: 'FORBIDDEN', message: 'Sin permiso.', correlationId: '' })); api.listFormDefinitions.mockResolvedValue([]); render(<MemoryRouter><ContextualFormsPage config={CONTEXTUAL_FORM_BRANCHES.activities} /></MemoryRouter>); expect(await screen.findByRole('alert')).toHaveTextContent('Sin permiso.'); });
  it('transmite el subproceso seleccionado al enlace Responder', async () => { renderPage(CONTEXTUAL_FORM_BRANCHES.production); const user = userEvent.setup(); await screen.findByText('Producción'); await user.selectOptions(screen.getByLabelText('Subproceso'), 'RECORRIDOS'); expect(screen.getByRole('link', { name: 'Responder' })).toHaveAttribute('href', expect.stringContaining('id_destino_respuesta=rounds')); });
  it('consulta respuestas exclusivamente para el subproceso seleccionado', async () => { renderPage(CONTEXTUAL_FORM_BRANCHES.production); const user = userEvent.setup(); await screen.findByText('Producción'); await user.selectOptions(screen.getByLabelText('Subproceso'), 'RECORRIDOS'); await waitFor(() => expect(api.listDestinationResponses).toHaveBeenCalledWith('rounds')); });
});
