import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { HttpError } from '../../api/client';
import { DynamicResponsePage } from './DynamicResponsePage';

const api = vi.hoisted(() => ({ getFormDefinition: vi.fn(), getFormResponse: vi.fn(), listDestinationTree: vi.fn(), saveFormResponse: vi.fn() }));
vi.mock('../../api/formBuilder', async () => ({ ...await vi.importActual<typeof import('../../api/formBuilder')>('../../api/formBuilder'), ...api }));
vi.mock('../../components/FeedbackProvider', () => ({ useFeedback: () => ({ notify: vi.fn(), confirm: vi.fn().mockResolvedValue(true) }) }));
vi.mock('../../components/useUnsavedChanges', () => ({ useUnsavedChanges: vi.fn() }));
const leaf = (id: string, codigo: string, nombre: string) => ({ id_destino: id, codigo, nombre, nivel: 'SUBPROCESO' as const, padre_id_destino: 'p', activo: true, orden: 1, hijos: [] });
const tree = [{ id_destino: 'ts', codigo: 'TRABAJO_SOCIAL', nombre: 'Trabajo Social', nivel: 'MACROPROCESO' as const, padre_id_destino: null, activo: true, orden: 1, hijos: [{ id_destino: 'prod', codigo: 'PRODUCCION', nombre: 'Producción', nivel: 'PROCESO' as const, padre_id_destino: 'ts', activo: true, orden: 1, hijos: [leaf('rounds', 'RECORRIDOS', 'Recorridos'), leaf('news', 'NOVEDADES_PLANTA', 'Novedades de planta')] }] }];
const definition = (ids: string[]) => ({ id_formulario: 'f1', nombre: 'Inspección', descripcion: null, responsable: null, estado: 'PUBLICADO' as const, fecha_publicacion: null, fecha_actualizacion: null, actualizado_por: null, permite_multiples_respuestas: false, version_publicada: 1, version: 1, activo: true, eliminado: false, destinos: [], destinos_jerarquicos: ids, total_preguntas: 0, total_respuestas: 0, secciones: [], preguntas: [], reglas: [] });
const saved = (destination: string | null) => ({ id_respuesta: 'r1', id_formulario: 'f1', numero_secuencial: 1, codigo_respuesta: 'TTHH_01', estado: 'REGISTRADO' as const, fecha_respuesta: '2026-01-01', usuario_respuesta: 'user', contexto_tipo: 'GENERAL', contexto_id: null, version: 1, id_destino_respuesta: destination });
function page(query = '', ids = ['rounds', 'news'], existing: ReturnType<typeof saved> | null = null) { api.getFormDefinition.mockResolvedValue(definition(ids)); api.listDestinationTree.mockResolvedValue(tree); api.getFormResponse.mockResolvedValue(existing); api.saveFormResponse.mockImplementation(async (_id: string, payload: { id_destino_respuesta: string | null }) => saved(payload.id_destino_respuesta)); render(<MemoryRouter initialEntries={[`/formularios/f1/responder${query}`]}><Routes><Route path="/formularios/:id/responder" element={<DynamicResponsePage />} /></Routes></MemoryRouter>); }
describe('Destino real de DynamicResponsePage', () => {
  beforeEach(() => vi.clearAllMocks());
  it('selecciona automáticamente el único destino y muestra su ruta', async () => { page('', ['rounds']); expect(await screen.findByText(/Trabajo Social → Producción → Recorridos/)).toBeInTheDocument(); });
  it('envía el destino único en el request', async () => { page('', ['rounds']); const user = userEvent.setup(); await screen.findByText('Inspección'); await user.click(screen.getByRole('button', { name: 'Enviar formulario' })); await waitFor(() => expect(api.saveFormResponse).toHaveBeenCalledWith('f1', expect.objectContaining({ id_destino_respuesta: 'rounds' }))); });
  it('usa el destino contextual inequívoco de Recorridos', async () => { page('?id_destino_respuesta=rounds&proceso_contextual=PRODUCCION'); const user = userEvent.setup(); await screen.findByText('Inspección'); await user.click(screen.getByRole('button', { name: 'Enviar formulario' })); await waitFor(() => expect(api.saveFormResponse).toHaveBeenCalledWith('f1', expect.objectContaining({ id_destino_respuesta: 'rounds' }))); });
  it('usa el destino contextual inequívoco de Novedades', async () => { page('?id_destino_respuesta=news&proceso_contextual=PRODUCCION'); const user = userEvent.setup(); await screen.findByText('Inspección'); await user.click(screen.getByRole('button', { name: 'Enviar formulario' })); await waitFor(() => expect(api.saveFormResponse).toHaveBeenCalledWith('f1', expect.objectContaining({ id_destino_respuesta: 'news' }))); });
  it('desde Todos exige seleccionar un destino multidestino', async () => { page(); const user = userEvent.setup(); await screen.findByLabelText('¿Dónde se registrará esta respuesta?'); await user.click(screen.getByRole('button', { name: 'Enviar formulario' })); expect(await screen.findByRole('alert')).toHaveTextContent('Seleccione un destino válido'); expect(api.saveFormResponse).not.toHaveBeenCalled(); });
  it('solo muestra destinos asignados y de la rama contextual', async () => { page('?proceso_contextual=PRODUCCION'); const select = await screen.findByLabelText('¿Dónde se registrará esta respuesta?'); expect(select).toHaveTextContent('Recorridos'); expect(select).toHaveTextContent('Novedades de planta'); });
  it('permite elegir uno de los destinos válidos desde Todos', async () => { page(); const user = userEvent.setup(); const select = await screen.findByLabelText('¿Dónde se registrará esta respuesta?'); await user.selectOptions(select, 'news'); await user.click(screen.getByRole('button', { name: 'Enviar formulario' })); await waitFor(() => expect(api.saveFormResponse).toHaveBeenCalledWith('f1', expect.objectContaining({ id_destino_respuesta: 'news' }))); });
  it('no inventa destino para un formulario histórico', async () => { page('', []); const user = userEvent.setup(); await screen.findByText('Inspección'); await user.click(screen.getByRole('button', { name: 'Enviar formulario' })); await waitFor(() => expect(api.saveFormResponse).toHaveBeenCalledWith('f1', expect.objectContaining({ id_destino_respuesta: null }))); });
  it('mantiene Persona y contexto en el request', async () => { page('?id_destino_respuesta=rounds&proceso_contextual=PRODUCCION&id_persona=p1&crear_contexto=1'); const user = userEvent.setup(); await screen.findByText('Inspección'); await user.click(screen.getByRole('button', { name: 'Enviar formulario' })); await waitFor(() => expect(api.saveFormResponse).toHaveBeenCalledWith('f1', expect.objectContaining({ id_persona: 'p1', crear_contexto: true, contexto_tipo: 'GENERAL' }))); });
  it('incluye el destino también al guardar borrador', async () => { page('?id_destino_respuesta=rounds&proceso_contextual=PRODUCCION'); const user = userEvent.setup(); await screen.findByText('Inspección'); await user.click(screen.getByRole('button', { name: 'Guardar borrador' })); await waitFor(() => expect(api.saveFormResponse).toHaveBeenCalledWith('f1', expect.objectContaining({ borrador: true, id_destino_respuesta: 'rounds' }))); });
  it('rechaza un destino contextual no válido antes de enviar', async () => { page('?id_destino_respuesta=unknown&proceso_contextual=PRODUCCION'); const user = userEvent.setup(); await screen.findByLabelText('¿Dónde se registrará esta respuesta?'); await user.click(screen.getByRole('button', { name: 'Enviar formulario' })); expect(await screen.findByRole('alert')).toHaveTextContent('Seleccione un destino válido'); expect(api.saveFormResponse).not.toHaveBeenCalled(); });
  it('informa cuando la rama no ofrece destinos válidos', async () => { page('?proceso_contextual=DEPARTAMENTO_MEDICO'); const user = userEvent.setup(); await screen.findByLabelText('¿Dónde se registrará esta respuesta?'); await user.click(screen.getByRole('button', { name: 'Enviar formulario' })); expect(await screen.findByRole('alert')).toHaveTextContent('No hay destinos válidos'); });
  it('muestra loading mientras carga árbol y definición', () => { api.getFormDefinition.mockReturnValue(new Promise(() => undefined)); api.listDestinationTree.mockReturnValue(new Promise(() => undefined)); api.getFormResponse.mockResolvedValue(null); render(<MemoryRouter initialEntries={['/formularios/f1/responder']}><Routes><Route path="/formularios/:id/responder" element={<DynamicResponsePage />} /></Routes></MemoryRouter>); expect(screen.getByText('Cargando formulario…')).toBeInTheDocument(); });
  it('muestra un 403 del backend', async () => { api.getFormDefinition.mockResolvedValue(definition(['rounds'])); api.listDestinationTree.mockRejectedValue(new HttpError(403, { ok: false, code: 'FORBIDDEN', message: 'Sin permiso.', correlationId: '' })); api.getFormResponse.mockResolvedValue(null); render(<MemoryRouter initialEntries={['/formularios/f1/responder']}><Routes><Route path="/formularios/:id/responder" element={<DynamicResponsePage />} /></Routes></MemoryRouter>); expect(await screen.findByText('Sin permiso.')).toBeInTheDocument(); });
  it('muestra un 401 del backend', async () => { api.getFormDefinition.mockResolvedValue(definition(['rounds'])); api.listDestinationTree.mockRejectedValue(new HttpError(401, { ok: false, code: 'SESSION_REQUIRED', message: 'Inicie sesión.', correlationId: '' })); api.getFormResponse.mockResolvedValue(null); render(<MemoryRouter initialEntries={['/formularios/f1/responder']}><Routes><Route path="/formularios/:id/responder" element={<DynamicResponsePage />} /></Routes></MemoryRouter>); expect(await screen.findByText('Inicie sesión.')).toBeInTheDocument(); });
  it('evita doble submit mientras guarda', async () => { page('?id_destino_respuesta=rounds&proceso_contextual=PRODUCCION'); let done!: (value: ReturnType<typeof saved>) => void; api.saveFormResponse.mockReturnValue(new Promise((resolve) => { done = resolve; })); const user = userEvent.setup(); await screen.findByText('Inspección'); await user.click(screen.getByRole('button', { name: 'Enviar formulario' })); expect(api.saveFormResponse).toHaveBeenCalledOnce(); expect(screen.getAllByRole('button', { name: 'Guardando…' })).toHaveLength(2); done(saved('rounds')); });
  it('conserva el destino original de una respuesta existente', async () => { page('?respuesta=r1&editar=1', ['rounds', 'news'], saved('rounds')); expect(await screen.findByText(/Trabajo Social → Producción → Recorridos/)).toBeInTheDocument(); expect(screen.queryByLabelText('¿Dónde se registrará esta respuesta?')).not.toBeInTheDocument(); });
});
