import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { canAccess } from '../../api/auth';
import { HttpError } from '../../api/client';
import { createFormDefinition, deleteFormDefinition, duplicateFormDefinition, listDestinationTree, listFormDefinitions, setFormStatus, type FormDefinition, type FormDestinationNode } from '../../api/formBuilder';
import { useAuth } from '../../app/AuthContext';
import { Modal } from '../../components/Modal';
import { useFeedback } from '../../components/FeedbackProvider';
import { formatDateTime } from '../../utils/dates';
import { destinationPaths } from './HierarchicalDestinationPicker';

const legacyLabels: Record<string, string> = { GENERAL: 'General', CASOS: 'Casos', ATENCIONES: 'Atenciones', NOVEDADES: 'Novedades', RECORRIDOS: 'Recorridos', PERSONAS: 'Personas' };
function flatten(tree: FormDestinationNode[]): FormDestinationNode[] { return tree.flatMap((node) => [node, ...flatten(node.hijos)]); }

export function FormulariosAdminPage() {
  const navigate = useNavigate(); const { notify, confirm } = useFeedback(); const { usuario } = useAuth();
  const canCreate = canAccess(usuario, 'FORMULARIOS', 'create'); const canEdit = canAccess(usuario, 'FORMULARIOS', 'edit');
  const [forms, setForms] = useState<FormDefinition[]>([]); const [tree, setTree] = useState<FormDestinationNode[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [macro, setMacro] = useState(''); const [process, setProcess] = useState(''); const [subprocess, setSubprocess] = useState('');
  const [creating, setCreating] = useState(false); const [creatingForm, setCreatingForm] = useState(false); const [name, setName] = useState(''); const [description, setDescription] = useState('');
  const [formToDelete, setFormToDelete] = useState<FormDefinition | null>(null); const [deleting, setDeleting] = useState(false);
  async function load() { setLoading(true); setError(null); try { const [items, catalog] = await Promise.all([listFormDefinitions(), listDestinationTree()]); setForms(items); setTree(catalog); } catch (err) { setError(err instanceof HttpError ? err.message : 'No fue posible cargar el repositorio de formularios.'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  const nodes = useMemo(() => flatten(tree), [tree]); const paths = useMemo(() => destinationPaths(tree), [tree]);
  const parent = useMemo(() => new Map(nodes.map((node) => [node.id_destino, node.padre_id_destino])), [nodes]);
  const processes = nodes.filter((node) => node.nivel === 'PROCESO' && (!macro || node.padre_id_destino === macro));
  const subprocesses = nodes.filter((node) => node.nivel === 'SUBPROCESO' && (!process || node.padre_id_destino === process));
  const filtered = useMemo(() => forms.filter((form) => { const ids = form.destinos_jerarquicos ?? []; return (!query || `${form.nombre} ${form.descripcion ?? ''}`.toLowerCase().includes(query.toLowerCase())) && (!status || form.estado === status) && (!macro || ids.some((id) => parent.get(parent.get(id) ?? '') === macro)) && (!process || ids.some((id) => parent.get(id) === process)) && (!subprocess || ids.includes(subprocess)); }), [forms, query, status, macro, process, subprocess, parent]);
  async function create(event: FormEvent) { event.preventDefault(); if (creatingForm) return; setCreatingForm(true); try { const form = await createFormDefinition({ nombre: name, descripcion: description || null, destinos: [] }); notify('Formulario creado. Gestione sus destinos jerárquicos en el constructor.'); navigate(`/formularios/${form.id_formulario}`); } catch (err) { setError(err instanceof HttpError ? err.message : 'No fue posible crear el formulario.'); } finally { setCreatingForm(false); } }
  async function changeStatus(form: FormDefinition, next: string) { if (!canEdit) return; if (next !== 'PUBLICADO' && !await confirm({ title: next === 'ARCHIVADO' ? 'Archivar formulario' : 'Despublicar formulario', message: 'El formulario dejará de estar disponible para nuevas respuestas.', confirmLabel: next === 'ARCHIVADO' ? 'Archivar' : 'Despublicar', danger: true })) return; try { await setFormStatus(form.id_formulario, next, form.version); await load(); notify('Estado actualizado.'); } catch (err) { notify(err instanceof HttpError ? err.message : 'No fue posible cambiar el estado.', 'error'); } }
  function requestDelete(form: FormDefinition) { if (form.estado === 'PUBLICADO') { notify('Debe despublicar el formulario antes de eliminarlo.', 'error'); return; } if (form.total_respuestas > 0) { notify('Este formulario no puede eliminarse porque contiene respuestas registradas. Puede archivarlo para conservar su historial.', 'error'); return; } setFormToDelete(form); }
  async function removeForm() { if (!formToDelete || deleting) return; setDeleting(true); try { await deleteFormDefinition(formToDelete.id_formulario, formToDelete.version); setForms((items) => items.filter((item) => item.id_formulario !== formToDelete.id_formulario)); setFormToDelete(null); notify('Formulario eliminado correctamente.'); } catch (err) { notify(err instanceof HttpError ? err.message : 'No fue posible eliminar el formulario.', 'error'); } finally { setDeleting(false); } }
  function clearFilters() { setQuery(''); setStatus(''); setMacro(''); setProcess(''); setSubprocess(''); }
  return <div className="forms-admin-page"><section className="panel forms-heading"><div><p className="eyebrow">Repositorio central</p><h2>Formularios</h2><p>Plantillas únicas reutilizables en Trabajo Social.</p></div>{canCreate && <button type="button" onClick={() => setCreating(true)}>+ Crear formulario</button>}</section>
    {error && <p className="form-error" role="alert">{error}</p>}<section className="panel form-filters"><label className="visually-hidden" htmlFor="search-form">Buscar formulario</label><input id="search-form" placeholder="Buscar formulario…" value={query} onChange={(e) => setQuery(e.target.value)} /><select aria-label="Filtrar por estado" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Todos los estados</option><option value="BORRADOR">Borrador</option><option value="PUBLICADO">Publicado</option><option value="INACTIVO">Inactivo</option><option value="ARCHIVADO">Archivado</option></select><select aria-label="Filtrar por macroproceso" value={macro} onChange={(e) => { setMacro(e.target.value); setProcess(''); setSubprocess(''); }}><option value="">Todos los macroprocesos</option>{nodes.filter((node) => node.nivel === 'MACROPROCESO').map((node) => <option key={node.id_destino} value={node.id_destino}>{node.nombre}</option>)}</select><select aria-label="Filtrar por proceso" value={process} onChange={(e) => { setProcess(e.target.value); setSubprocess(''); }}><option value="">Todos los procesos</option>{processes.map((node) => <option key={node.id_destino} value={node.id_destino}>{node.nombre}</option>)}</select><select aria-label="Filtrar por subproceso" value={subprocess} onChange={(e) => setSubprocess(e.target.value)}><option value="">Todos los subprocesos</option>{subprocesses.map((node) => <option key={node.id_destino} value={node.id_destino}>{node.nombre}</option>)}</select><button type="button" className="secondary" onClick={clearFilters}>Limpiar filtros</button></section>
    {loading ? <p className="loading-message">Cargando formularios…</p> : filtered.length === 0 ? <div className="panel empty-state"><strong>No se encontraron formularios</strong><p>Ajuste los filtros o cree una nueva plantilla.</p></div> : <div className="form-cards">{filtered.map((form) => <article className="form-card" key={form.id_formulario}><div className="form-card-top"><span className={`badge status-${form.estado.toLowerCase()}`}>{form.estado}</span><span className="form-card-date">Actualizado {formatDateTime(form.fecha_actualizacion)}</span></div><h3>{form.nombre}</h3><p>{form.descripcion || 'Sin descripción.'}</p><div className="form-destinations">{(form.destinos_jerarquicos ?? []).map((id) => <span key={id}>{paths.get(id) ?? id}</span>)}{form.destinos.map((item) => <span key={`legacy-${item}`}>Destino histórico sin clasificación jerárquica: {legacyLabels[item] ?? item}</span>)}{!form.destinos.length && !(form.destinos_jerarquicos ?? []).length && <span>Sin destinos asignados</span>}</div><dl className="form-metrics"><div><dt>Preguntas</dt><dd>{form.total_preguntas}</dd></div><div><dt>Respuestas</dt><dd>{form.total_respuestas}</dd></div><div><dt>Versión</dt><dd>{form.version_publicada || '—'}</dd></div></dl><div className="form-card-actions">{canEdit && form.estado !== 'ARCHIVADO' && <button type="button" onClick={() => navigate(`/formularios/${form.id_formulario}`)}>Editar y gestionar destinos</button>}<button type="button" className="secondary" onClick={() => navigate(`/formularios/${form.id_formulario}`, { state: { tab: 'vista-previa' } })}>Vista previa</button><button type="button" className="secondary" onClick={() => navigate(`/formularios/${form.id_formulario}`, { state: { tab: 'respuestas' } })}>Respuestas</button>{canEdit && <button type="button" className="secondary" onClick={async () => { try { const copy = await duplicateFormDefinition(form.id_formulario); notify('Formulario duplicado.'); navigate(`/formularios/${copy.id_formulario}`); } catch (err) { notify(err instanceof HttpError ? err.message : 'No fue posible duplicar.', 'error'); } }}>Duplicar</button>}{canEdit && (form.estado === 'PUBLICADO' ? <button type="button" className="ghost" onClick={() => void changeStatus(form, 'INACTIVO')}>Despublicar</button> : form.estado !== 'ARCHIVADO' && <button type="button" className="ghost" disabled={!form.total_preguntas} onClick={() => void changeStatus(form, 'PUBLICADO')}>Publicar</button>)}{canEdit && form.acciones?.eliminar && <button type="button" className="ghost ghost-danger" onClick={() => requestDelete(form)}>Eliminar</button>}</div></article>)}</div>}
    {creating && <Modal titulo="Crear formulario" onClose={() => !creatingForm && setCreating(false)} size="medium"><form onSubmit={create}><label htmlFor="new-form-name">Nombre</label><input id="new-form-name" required data-autofocus value={name} onChange={(e) => setName(e.target.value)} /><label htmlFor="new-form-description">Descripción</label><textarea id="new-form-description" value={description} onChange={(e) => setDescription(e.target.value)} /><p className="footnote">Tras crearlo podrá asignar uno o varios destinos jerárquicos en el constructor.</p><div className="modal-actions"><button type="button" className="secondary" disabled={creatingForm} onClick={() => setCreating(false)}>Cancelar</button><button type="submit" disabled={creatingForm}>{creatingForm ? 'Creando…' : 'Crear formulario'}</button></div></form></Modal>}
    {formToDelete && <Modal titulo="Eliminar formulario" onClose={() => !deleting && setFormToDelete(null)} size="small" closeOnBackdrop={!deleting}><p className="dialog-message">¿Está seguro de que desea eliminar este formulario?</p><p><strong>{formToDelete.nombre}</strong></p><p className="inline-alert">Esta acción eliminará el formulario de los listados del sistema.</p><div className="modal-actions"><button type="button" className="secondary" disabled={deleting} onClick={() => setFormToDelete(null)}>Cancelar</button><button type="button" className="danger" disabled={deleting} onClick={() => void removeForm()}>{deleting ? 'Eliminando…' : 'Eliminar'}</button></div></Modal>}
  </div>;
}
