import { useEffect, useState, type FormEvent } from 'react';
import { crearAccidente, analizarArchivoAccidentes, confirmarLoteAccidentes, listarAccidentes, listarIncidenciasAccidente, listarLotesAccidentes, type Accidente, type AccidenteEstado, type IncidenciaAccidente, type LoteAccidente } from '../../api/accidentes';
import { Modal } from '../../components/Modal';
import { useFeedback } from '../../components/FeedbackProvider';

const pageSize = 25;
export function AccidentesPage() {
  const { notify, confirm } = useFeedback(); const [tab, setTab] = useState<'registros'|'importar'|'historial'>('registros'); const [records, setRecords] = useState<Accidente[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(0); const [filters, setFilters] = useState({nombre:'', cedula:'', clasificacion:'', estado:''}); const [error, setError] = useState<string | null>(null); const [detail, setDetail] = useState<Accidente | null>(null); const [lots, setLots] = useState<LoteAccidente[]>([]); const [selectedLot, setSelectedLot] = useState<LoteAccidente | null>(null); const [issues, setIssues] = useState<IncidenciaAccidente[]>([]); const [file, setFile] = useState<File | null>(null); const [analysis, setAnalysis] = useState<{lote:LoteAccidente;puede_confirmarse:boolean}|null>(null); const [manual, setManual] = useState(false);
  const loadRecords = async (p=page) => { try { setError(null); const params = new URLSearchParams({limite:String(pageSize),offset:String(p*pageSize)}); Object.entries(filters).forEach(([key,value]) => value && params.set(key,value)); const data = await listarAccidentes(params); setRecords(data.items); setTotal(data.total); } catch { setError('No fue posible cargar los Accidentes.'); } };
  const loadLots = async () => { try { const data = await listarLotesAccidentes(new URLSearchParams({limite:'25',offset:'0'})); setLots(data.items); } catch { setError('No fue posible cargar el historial.'); } };
  useEffect(() => { if (tab === 'registros') void loadRecords(); if (tab === 'historial') void loadLots(); }, [tab,page]);
  const showLot = async (lot: LoteAccidente) => { setSelectedLot(lot); try { setIssues((await listarIncidenciasAccidente(lot.id_lote)).items); } catch { setIssues([]); } };
  const submitManual = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); try { await crearAccidente({persona_id:String(data.get('persona_id')),fecha_accidente:String(data.get('fecha_accidente')),clasificacion:String(data.get('clasificacion')),descripcion:String(data.get('descripcion')),estado:String(data.get('estado')) as AccidenteEstado,observacion:String(data.get('observacion') || '') || null}); setManual(false); notify('Accidente registrado correctamente.'); await loadRecords(0); setPage(0); } catch { setError('No fue posible registrar el accidente. Verifique la Persona y los campos.'); } };
  const analyze = async () => { if (!file) return; try { const data = await analizarArchivoAccidentes(file); setAnalysis({lote:data.lote,puede_confirmarse:data.puede_confirmarse}); setSelectedLot(data.lote); setIssues([]); notify('Archivo analizado. Revise el resultado antes de confirmar.', 'info'); } catch (err) { setError(err instanceof Error ? err.message : 'No fue posible analizar el archivo.'); } };
  const confirmImport = async () => { if (!analysis || !await confirm({title:'Confirmar importación',message:'Se crearán los Accidentes válidos del lote.',confirmLabel:'Confirmar'})) return; try { const lot = await confirmarLoteAccidentes(analysis.lote.id_lote); setAnalysis({lote:lot,puede_confirmarse:false}); setSelectedLot(lot); notify('Importación confirmada correctamente.'); } catch { setError('No fue posible confirmar el lote.'); } };
  return <section className="module-operational-page accidentes-page"><header className="module-page-hero"><div><p className="eyebrow">Trabajo Social · Departamento Médico</p><h2>Accidentes</h2><p>Registro manual e importación XLSX con revisión previa.</p></div></header><div className="tabs module-tabs" role="tablist">{(['registros','importar','historial'] as const).map(value=><button key={value} type="button" role="tab" aria-selected={tab===value} onClick={()=>setTab(value)}>{value==='registros'?'Registros':value==='importar'?'Importar XLSX':'Historial'}</button>)}</div>{error&&<p className="form-error" role="alert">{error}</p>}
    {tab==='registros'&&<section className="panel module-table-card"><div className="panel-header"><div><h3>Registros operativos</h3><p className="footnote">Accidentes registrados en el sistema.</p></div><button onClick={()=>setManual(true)}>Registrar accidente</button></div><form className="form-grid module-filter-card" onSubmit={e=>{e.preventDefault();setPage(0);void loadRecords(0);}}>{(['nombre','cedula','clasificacion'] as const).map(key=><label key={key}>{key[0].toUpperCase()+key.slice(1)}<input value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}/></label>)}<label>Estado<select value={filters.estado} onChange={e=>setFilters({...filters,estado:e.target.value})}><option value="">Todos</option><option>ABIERTO</option><option>EN_SEGUIMIENTO</option><option>CERRADO</option></select></label><div className="button-row"><button>Aplicar filtros</button><button type="button" className="secondary" onClick={()=>{setFilters({nombre:'',cedula:'',clasificacion:'',estado:''});setPage(0);void loadRecords(0);}}>Limpiar</button></div></form><div className="table-scroll"><table className="data-table module-data-table"><thead><tr><th>Persona</th><th>Fecha</th><th>Clasificación</th><th>Estado</th><th>Origen</th><th/></tr></thead><tbody>{records.map(record=><tr key={record.id_accidente}><td>{record.persona}</td><td>{record.fecha_accidente}</td><td>{record.clasificacion}</td><td><span className="badge">{record.estado}</span></td><td>{record.origen}</td><td><button className="secondary" onClick={()=>setDetail(record)}>Ver detalle</button></td></tr>)}</tbody></table></div><div className="pagination-controls module-pagination"><button className="secondary" disabled={!page} onClick={()=>setPage(page-1)}>Anterior</button><span>{total ? `${page*pageSize+1}-${Math.min(total,(page+1)*pageSize)} de ${total}`:'0 registros'}</span><button className="secondary" disabled={(page+1)*pageSize>=total} onClick={()=>setPage(page+1)}>Siguiente</button></div></section>}
    {tab==='importar'&&<section className="panel"><h3>Importar XLSX</h3><p className="footnote">Columnas: cedula, fecha_accidente, clasificacion, descripcion; estado y observacion son opcionales.</p><input aria-label="Archivo XLSX de Accidentes" type="file" accept=".xlsx" onChange={e=>setFile(e.target.files?.[0]??null)}/><button disabled={!file} onClick={()=>void analyze()}>Analizar archivo</button>{analysis&&<div className="analysis-detail"><p><strong>{analysis.lote.nombre_archivo}</strong> · válidas: {analysis.lote.filas_validas} · errores: {analysis.lote.filas_con_error} · duplicadas: {analysis.lote.filas_duplicadas}</p>{analysis.puede_confirmarse&&<button onClick={()=>void confirmImport()}>Confirmar importación</button>}</div>}</section>}
    {tab==='historial'&&<section className="panel"><h3>Historial de importaciones</h3><div className="table-scroll"><table className="data-table"><thead><tr><th>Archivo</th><th>Estado</th><th>Total</th><th>Importadas</th><th/></tr></thead><tbody>{lots.map(lot=><tr key={lot.id_lote}><td>{lot.nombre_archivo}</td><td>{lot.estado}</td><td>{lot.total_filas}</td><td>{lot.filas_importadas}</td><td><button className="secondary" onClick={()=>void showLot(lot)}>Ver incidencias</button></td></tr>)}</tbody></table></div>{selectedLot&&<div className="lot-detail"><h3>{selectedLot.nombre_archivo}</h3>{issues.length?<ul>{issues.map(issue=><li key={issue.id_error}>Fila {issue.numero_fila}: {issue.mensaje}</li>)}</ul>:<p className="footnote">Sin incidencias registradas.</p>}</div>}</section>}
    {manual&&<Modal titulo="Registrar accidente" onClose={()=>setManual(false)}><form onSubmit={submitManual} className="form-grid"><label>ID de Persona<input name="persona_id" required/></label><label>Fecha<input name="fecha_accidente" type="date" required/></label><label>Clasificación<input name="clasificacion" required/></label><label>Estado<select name="estado" defaultValue="ABIERTO"><option>ABIERTO</option><option>EN_SEGUIMIENTO</option><option>CERRADO</option></select></label><label className="full-width">Descripción<textarea name="descripcion" required/></label><label className="full-width">Observación<textarea name="observacion"/></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setManual(false)}>Cancelar</button><button>Guardar</button></div></form></Modal>}{detail&&<Modal titulo="Detalle de accidente" onClose={()=>setDetail(null)}><dl className="field-list">{Object.entries({Persona:detail.persona,Fecha:detail.fecha_accidente,Clasificación:detail.clasificacion,Estado:detail.estado,Descripción:detail.descripcion,Observación:detail.observacion??'—',Origen:detail.origen}).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></Modal>}</section>;
}
