/** Datos extraídos de PREGUNTAS Y RESPUESTA DEL FORMULARIO.xlsx. */
function matrizPreguntasYOpciones_() {
  return {
    "ArchivoFuente": "PREGUNTAS Y RESPUESTA DEL FORMULARIO.xlsx",
    "HojaFuente": "Hoja1",
    "RangoFuente": "A1:X215",
    "ColumnasIgnoradas": [
      "Tipo de elemento",
      "Ruta de acceso"
    ],
    "Preguntas": [
      {
        "Orden": 1,
        "Etiqueta": "CodigoCaso",
        "Tipo": "CAMPO_OCULTO",
        "Categoria": "DATOS_CASO",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": true,
        "Opciones": [],
        "ValorPredeterminado": "",
        "TextoAyuda": ""
      },
      {
        "Orden": 2,
        "Etiqueta": "Responsable",
        "Tipo": "LISTA_DESPLEGABLE",
        "Categoria": "DATOS_CASO",
        "Obligatoria": true,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [
          "CATAGUA OCHOA JENNIFER ELIANI",
          "LUCAS ROSADO MELANY ANAHI",
          "MORAN QUINTEROS JEAN CARLOS",
          "OLAYA PISPIRA THALIA GUADALUPE",
          "SALAS VELEZ LUIGGI GABRIEL",
          "SESME JIMENEZ MELANY MICHELLE",
          "TOMALA QUIMI ANGIE GUADALUPE",
          "VILLAMAR FUENTES MARIO OMAR",
          "ZAMBRANO COLOMA ERICKA JAMILETH"
        ],
        "Catalogo": "RESPONSABLE",
        "TextoAyuda": "Seleccione el responsable."
      },
      {
        "Orden": 3,
        "Etiqueta": "Fecha y Hora",
        "Tipo": "FECHA_HORA",
        "Categoria": "DATOS_CASO",
        "Obligatoria": true,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": []
      },
      {
        "Orden": 4,
        "Etiqueta": "Tipo de Caso",
        "Tipo": "LISTA_DESPLEGABLE",
        "Categoria": "DATOS_CASO",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [
          "Individual (1 colaborador)",
          "Grupales (2 -25 colaboradores)",
          "Colectivo (25 a más colaboradores)"
        ],
        "Catalogo": "TIPO_CASO"
      },
      {
        "Orden": 5,
        "Etiqueta": "Prioridad",
        "Tipo": "LISTA_DESPLEGABLE",
        "Categoria": "DATOS_CASO",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [
          "Alta",
          "Media",
          "Baja"
        ],
        "Catalogo": "PRIORIDAD"
      },
      {
        "Orden": 6,
        "Etiqueta": "Tipo de gestión",
        "Tipo": "LISTA_DESPLEGABLE",
        "Categoria": "DATOS_CASO",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [
          "Accidente",
          "Alimentación",
          "Asignación externa",
          "Asistencia al IESS",
          "Asuntos escolares de hijos",
          "Atraso",
          "Calamidad doméstica",
          "Calamidad doméstica por hospitalización o enfermedad grave de familiar",
          "Calamidad doméstica por robo, secuestro, violación, intimidación o extorsión",
          "Calamidad doméstica por siniestro",
          "Cambio de domicilio",
          "Cambio de turno",
          "Cansancio",
          "Cuidado de hijos",
          "Daño a la propiedad",
          "Descanso médico emitido por SONGA",
          "Estado etílico",
          "Eventos",
          "Extorsión",
          "Falta injustificada",
          "Inseguridad",
          "Lavandería",
          "Libre no reportado",
          "Licencia por fallecimiento",
          "Licencia por maternidad",
          "Licencia por paternidad",
          "Licencia por servicio militar obligatorio",
          "Licencia por tratamiento médico de hijo con enfermedad catastrófica",
          "Notificación y control del embarazo",
          "Olvido o pérdida de credencial",
          "Oportunidad laboral",
          "Pago a terceros",
          "Permiso de lactancia",
          "Permiso excepcional sin documentación",
          "Permiso médico externo cuando no existe cobertura del IESS",
          "Permiso médico por accidente de trabajo",
          "Permiso médico por enfermedad general",
          "Permiso o descanso odontológico",
          "Permiso personal parcial",
          "Permiso personal total sin sueldo",
          "Permiso por estudio",
          "Permiso por requerimiento o notificación judicial",
          "Permiso por sufragio",
          "Préstamo por calamidad doméstica",
          "Problemas o trámites personales",
          "Retornado por control de seguridad",
          "Robo",
          "Salud del colaborador",
          "Salud familiar",
          "Se quedó del expreso",
          "Servicios básicos",
          "Vacaciones",
          "Viaje imprevisto"
        ],
        "Catalogo": "TIPO_GESTION"
      },
      {
        "Orden": 7,
        "Etiqueta": "EstadoCaso",
        "Tipo": "LISTA_DESPLEGABLE",
        "Categoria": "DATOS_CASO",
        "Obligatoria": true,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [
          "En acompañamiento",
          "En revisión",
          "En espera de información",
          "En espera de otra área",
          "Suspendido temporalmente",
          "Resuelto parcialmente",
          "Resuelto totalmente",
          "Cerrado",
          "Reabierto"
        ],
        "Catalogo": "ESTADO_CASO",
        "ValorPredeterminado": "",
        "TextoAyuda": "Seleccione el estado. Para cerrar un caso existente utilice la acción Cerrar caso."
      },
      {
        "Orden": 8,
        "Etiqueta": "Técnica/Instrumento de Bienestar Social",
        "Tipo": "LISTA_DESPLEGABLE",
        "Categoria": "DATOS_CASO",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [
          "Entrevista individual al colaborador",
          "Entrevista a jefe inmediato o supervisor",
          "Entrevista a testigos",
          "Entrevista familiar",
          "Entrevista grupal",
          "Visita domiciliaria",
          "Visita hospitalaria",
          "Observación directa en el lugar",
          "Seguimiento telefónico",
          "Revisión documental",
          "Estudio de caso",
          "Reunión interdisciplinaria",
          "Intervención en crisis",
          "Orientación social",
          "Mediación",
          "Acompañamiento social",
          "Coordinación interna",
          "Coordinación interinstitucional",
          "Derivación"
        ],
        "Catalogo": "TECNICA_INSTRUMENTO"
      },
      {
        "Orden": 9,
        "Etiqueta": "Coloqué el número de cédula del colaborador",
        "Tipo": "PERSONA",
        "Categoria": "DATOS_COLABORADOR",
        "Obligatoria": true,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [],
        "TextoAyuda": "Busque por cédula, nombre o código de empleado.",
        "Sensibilidad": "SI"
      },
      {
        "Orden": 10,
        "Etiqueta": "Sexo",
        "Tipo": "LISTA_DESPLEGABLE",
        "Categoria": "DATOS_COLABORADOR",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [
          "MASCULINO",
          "FEMENINO"
        ],
        "Catalogo": "SEXO",
        "Sensibilidad": "SI"
      },
      {
        "Orden": 11,
        "Etiqueta": "Cargo",
        "Tipo": "LISTA_DESPLEGABLE",
        "Categoria": "DATOS_COLABORADOR",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [
          "ABOGADO",
          "ADMINISTRADOR DE BASE DE DATOS",
          "ADMINISTRADOR DE COMEDOR",
          "ANALISTA DE LAB F-Q",
          "ANALISTA DE ALIANZAS CORPORATIVAS",
          "ANALISTA DE COSTOS",
          "ANALISTA DE DATA E INDICADOR",
          "ANALISTA DE EMPAQUE",
          "ANALISTA DE EMPAQUE Y FICHAS T",
          "ANALISTA DE LOGISTICA",
          "ANALISTA DE MEJORA CONTINUA",
          "ANALISTA DE NOMINA",
          "ANALISTA DE PRESUPUESTOS",
          "ANALISTA DE SELECC. Y DESA.",
          "ANALISTA DE SERV. PERSONAL",
          "ANALISTA DOCUMENTAL",
          "ANALISTA FINANCIERO SENIOR",
          "ANALISTA LAB MICRO",
          "ANALISTA ORGANOLEPTICOS",
          "ASISTENTE ADMINISTRATIVO",
          "ASISTENTE AUDITORIA PROCESOS",
          "ASISTENTE DE AUDITORIA",
          "ASISTENTE DE BODEGA",
          "ASISTENTE DE CAMARA",
          "ASISTENTE DE CONTABILIDAD",
          "ASISTENTE DE CONTROL CALIDAD",
          "ASISTENTE DE CONTROL Y PLANEAC",
          "ASISTENTE DE EMBARQUE",
          "ASISTENTE DE EXPORTACION",
          "ASISTENTE DE GERENCIA",
          "ASISTENTE DE GESTION DE CALIDA",
          "ASISTENTE DE LIMPIEZA",
          "ASISTENTE DE LIQUIDACIONES",
          "ASISTENTE DE LOGISTICA",
          "ASISTENTE DE MEJORA CONTINUA",
          "ASISTENTE DE NOMINA",
          "ASISTENTE DE PRESUPUESTOS",
          "ASISTENTE DE PRODUCCION",
          "ASISTENTE DE SEGURIDAD",
          "ASISTENTE DE TALENTO HUMANO",
          "ASISTENTE DE TESORERIA",
          "ASISTENTE DE VALORIZACION",
          "AUDITOR DE PROCESOS",
          "AUDITOR INTERNO ISO",
          "AUDITOR OPERATIVO",
          "AUXILIAR DE ENFERMERIA",
          "AUXILIAR DE TALENTO HUMANO",
          "AYUDANTE",
          "AYUDANTE DE BODEGA",
          "AYUDANTE DE COCINA",
          "AYUDANTE EMIS ETIQUETA",
          "AYUDANTE LIMPIEZA",
          "AYUDANTE ORGANOLEPTICO",
          "BODEGUERO",
          "CHOFER",
          "COCINERO",
          "COMPRADOR",
          "COMPRADOR TECNICO",
          "CONTADOR DE IMPUESTO",
          "CONTADOR FINANCIERO",
          "CONTADOR GENERAL",
          "CONTROLADOR DE MESA",
          "COORD. ADMINISTRATIVO",
          "COORD. DE RELACIONES LABORALES",
          "COORDI. SEGURIDAD",
          "COORDINADOR DE CERTIFICACIONES",
          "COORDINADOR DE COMPRAS DE SERVICIOS",
          "COORDINADOR DE COMUNICACION INTERNA",
          "COORDINADOR DE EMBARQUES",
          "COORDINADOR DE LIMPIEZA",
          "COORDINADOR DE NOMINA",
          "COORDINADOR DE TALENTO HUMANO",
          "COORDINADOR DOCUMENTARIO",
          "COORDINADOR MEDICO",
          "DESARROLLADOR SENIOR",
          "DESARROLLADOR WEB",
          "DIGITADOR DE DATOS",
          "DIRECTOR DE CALIDAD",
          "DIRECTOR DE MANTENIMIENTO",
          "DIRECTOR DE OPERACIONES",
          "DIRECTOR DE PRODUCCION",
          "ELECTRONICO DE PLANTA",
          "ENFERMERO",
          "ESPECIALISTA DE ALIANZAS CORPORATIVAS",
          "GERENTE ADMINISTRATIVO",
          "GERENTE DE COMPRAS",
          "GERENTE DE CONTROL DE CALIDAD",
          "GERENTE DE CONTROL Y PLANEACIO",
          "GERENTE DE EMBARQUE",
          "GERENTE DE EXPORTACION",
          "GERENTE DE LOGISTICA",
          "GERENTE DE MANTENIMIENTO",
          "GERENTE DE PRODUCCION",
          "GERENTE DE PROYECTOS",
          "GERENTE DE REFRIGERACION",
          "GERENTE DE SISTEMA DE GESTION",
          "GERENTE DE SISTEMAS",
          "GERENTE DE TESORERIA",
          "GERENTE DE VENTAS",
          "GERENTE FINANCIERO",
          "GERENTE GENERAL",
          "GERENTE SENIOR DE TH",
          "GESTOR DE AUDITORIA",
          "INGENIERO DE ORG Y METODOS",
          "INGENIERO DE PROYECTOS",
          "INGENIERO DE PROYECTOS JR",
          "INSPECTOR DE GESTION DE CALIDA",
          "JEFE ADMINISTRATIVO",
          "JEFE DE ABASTECIMIENTO Y EMPAQ",
          "JEFE DE ADM DE REMUNERACIONES",
          "JEFE DE AUDITORIA",
          "JEFE DE BODEGAS EXTERNAS",
          "JEFE DE CAMARA",
          "JEFE DE CERTIFICACIONES",
          "JEFE DE COCINA",
          "JEFE DE COMPRAS",
          "JEFE DE CONTROL DE CALIDAD",
          "JEFE DE COSTOS",
          "JEFE DE DESARROLLO",
          "JEFE DE DESCABEZADO",
          "JEFE DE EMBARQUE",
          "JEFE DE EMPAQUE",
          "JEFE DE FACTURACION Y DAE",
          "JEFE DE INFRAESTRUCTURA",
          "JEFE DE INVESTIGACION Y DESARR",
          "JEFE DE IQF.",
          "JEFE DE LABORATORIO",
          "JEFE DE LIMPIEZA",
          "JEFE DE LINEA",
          "JEFE DE LINEA BACK UP",
          "JEFE DE LIQUIDACIONES",
          "JEFE DE LOGISTICA EXPORTACION",
          "JEFE DE MANTENIMIENTO",
          "JEFE DE OPERACION Y LOGISTICA",
          "JEFE DE ORG Y METODOS",
          "JEFE DE PLANTA",
          "JEFE DE PRESUPUESTO",
          "JEFE DE REFRIGERACION",
          "JEFE DE RELACIONES LABORALES",
          "JEFE DE SEGURIDAD Y SALUD OCUP",
          "JEFE DE SELECCION Y DESARROLLO",
          "JEFE DE TESORERIA",
          "JEFE DE TRANSPORTE",
          "JEFE DE VALOR AGREGADO",
          "JEFE DOCUMENTAL",
          "LIDER HACCP AUDIT ISO",
          "LIQUIDADOR",
          "LIQUIDADOR DE PELADO",
          "MEDICO",
          "MENSAJERO",
          "METROLOGO",
          "MONITOR CALIDAD CAMARA",
          "MONITOR CALIDAD VA",
          "MONITOR DE CALIDAD",
          "MONITOR DE DESCONGELADO",
          "MONITOR DE PESCA",
          "OPERADOR DE COCIDO",
          "OPERADOR DE MAQUINA",
          "OPERADOR DE MONTACARGA",
          "PASANTE",
          "PESADOR",
          "PLANIFICADOR DE EMBARQUES",
          "PLANIFICADOR DE LOGISTICA",
          "PLANIFICADOR DE MANTENIMIENTO",
          "PLANIFICADOR DE PROYECTOS",
          "PLANIFICADOR SENIOR DE MANTENIMIENTO",
          "PRESIDENTE",
          "SERV GNRLES PRODUCCION",
          "SERV GRLES OPERACIONES",
          "SISTEMAS - DESARROLLO",
          "SUB GERENTE DE CAMARA",
          "SUB GERENTE DE EMBARQUES",
          "SUBGERENTE DE CALIDAD",
          "SUBGERENTE DE DESARROLLO",
          "SUBGERENTE DE LOGISTICA",
          "SUBGERENTE DE PRODUCCION",
          "SUPERVISOR BRINE",
          "SUPERVISOR CALIDAD CAMARA",
          "SUPERVISOR DE BODEGA",
          "SUPERVISOR DE CAJAS",
          "SUPERVISOR DE CAMARA",
          "SUPERVISOR DE DESCABEZADO",
          "SUPERVISOR DE GESTION DE CALIDAD E INOCUIDAD",
          "SUPERVISOR DE INFRAESTRUCTURA",
          "SUPERVISOR DE IQF",
          "SUPERVISOR DE LIMPIEZA",
          "SUPERVISOR DE LIQUIDADORES",
          "SUPERVISOR DE LOGISTICA",
          "SUPERVISOR DE MANT AUTOMOTRIZ",
          "SUPERVISOR DE MANTENIMIENTO",
          "SUPERVISOR DE PELADO",
          "SUPERVISOR DE PESADORES",
          "SUPERVISOR DE PRODUCCION",
          "SUPERVISOR DE REFRIGERACION",
          "SUPERVISOR DE RETRACTILADO",
          "SUPERVISOR DE TRANSPORTE",
          "SUPERVISOR ELECTRICO",
          "SUPERVISOR GENERAL",
          "SUPERVISOR LABORATORIO ORGA.",
          "SUPERVISOR MECANICO",
          "SUPERVISOR RECEPCION",
          "TEC. SENIOR INFRAES.",
          "TECNICO DE INFRAESTRUCTURA",
          "TECNICO DE MANTENIMIENTO",
          "TECNICO DE PLANOS",
          "TECNICO DE SEGURIDAD",
          "TECNICO DE SEGURIDAD JR",
          "TECNICO EN REFRIGERACION",
          "TECNICO JR SEGURIDAD",
          "TECNICO SR DE MANTENIMIENTO",
          "TESORERA",
          "TRABAJADOR SOCIAL",
          "TRAINEE",
          "TRAINEE DE SELECCION"
        ],
        "Catalogo": "CARGO"
      },
      {
        "Orden": 12,
        "Etiqueta": "Departamento",
        "Tipo": "LISTA_DESPLEGABLE",
        "Categoria": "DATOS_COLABORADOR",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [
          "ADMINISTRACION",
          "AUDITORIA INTERNA",
          "BODEGA",
          "CAMARA DE ALMACENAMIENTO",
          "COMEDOR",
          "COMPRAS",
          "CONTABILIDAD",
          "CONTROL CALIDAD FISICO QUIMICO",
          "CONTROL CALIDAD ORGANOLEPTICO",
          "CONTROL DE CALIDAD",
          "DEPARTAMENTO MEDICO",
          "DESARROLLO PRODUCTO",
          "EMBARQUE",
          "EXPORTACION",
          "FICHAS TECNICAS",
          "FINANCIERO",
          "GERENCIA GENERAL",
          "GESTION DE CALIDAD",
          "IQF",
          "LAVANDERIA",
          "LEGAL",
          "LIMPIEZA",
          "LIQUIDACIONES DE PRODUCTO",
          "LOGISTICA",
          "MANTENIMIENTO",
          "OPERACIONES",
          "PRESIDENCIA",
          "PRODUCCION",
          "PROYECTOS",
          "RETRACTILADO",
          "RRHH",
          "SEGURIDAD INDUSTRIAL",
          "SISTEMAS",
          "VALOR AGREGADO"
        ],
        "Catalogo": "DEPARTAMENTO"
      },
      {
        "Orden": 13,
        "Etiqueta": "Sub-centro",
        "Tipo": "LISTA_DESPLEGABLE",
        "Categoria": "DATOS_COLABORADOR",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [
          "ABASTECIMIENTO Y EMPAQUE",
          "ANALISIS Y PROGRAMACION",
          "AUDITORIA INTERNA",
          "AUTOMOTRIZ",
          "BAÑO PATIO",
          "BAÑO PATIO SONGA 2",
          "BODEGA OBRERO",
          "BODEGA SONGA 2 VA",
          "CAJAS",
          "CAMARA 1",
          "CAMARA OBRERO",
          "CAMARA SONGA 2 VA",
          "COMEDOR",
          "COMEDOR SONGA 2",
          "COMPRA DE CAMARON",
          "COMPRAS",
          "CONSULTORIO MEDICO",
          "CONTABILIDAD GENERAL",
          "CONTROL DE CALIDAD EXTERIORES",
          "CONTROL DE CALIDAD OBRERO",
          "CONTROL DE CALIDAD SONGA 2 VA",
          "CONTROL EXTERIORES",
          "DECORADO",
          "DEPARTAMENTO FINANCIERO",
          "DESARROLLO DE PRODUCTO",
          "DPTO BODEGA",
          "DPTO LAB FISICO QUIMICO",
          "DPTO LOGISTICA",
          "ELECTRICO",
          "ELECTRICO SONGA 2 VA",
          "EMBARQUE",
          "EMBARQUE OBRERO",
          "ETIQUETAS",
          "ETIQUETAS SONGA 2",
          "EXPORTACIONES",
          "FICHAS TECNICAS",
          "GERENCIA ADMINISTRATIVA",
          "GERENCIA FINANCIERA",
          "GERENCIA GENERAL",
          "GERENTE DE VENTAS",
          "IQF",
          "IQF SONGA 1",
          "LAB FISICO QUIMICO",
          "LAVANDERIA",
          "LAVANDERIA SONGA2",
          "LEGAL",
          "LIQUIDACION DE PROD. SONGA 2VA",
          "LIQUIDACIONES DE PRODUCTO",
          "LIQUIDACIONES PRODUCCION OBRER",
          "MANT.REFRIG. SONGA 2 VA",
          "MANTENIMIENTO",
          "MANTENIMIENTO ELECTRICO SERVIC",
          "MANTENIMIENTO MC CLASIFICADORA",
          "MANTENIMIENTO SONGA 2 VA",
          "MEJORA CONTINUA",
          "MICROBIOLOGIA",
          "OPERAC LOGISTICAS OBRERO",
          "OPERAC.LOGIS. PROD.SONGA 2 VA",
          "OPERACIONES",
          "OPERADOR DE MANTENIMIENTO",
          "PELADO SONGA 2 VA",
          "PRESIDENCIA",
          "PROD. CAJAS SONGA 2 VA",
          "PROD. DESCABEZADO SONGA 2 VA",
          "PROD. LIMPIEZA EXTERIOR",
          "PROD.LIMPIEZA INT.SONGA 2 VA",
          "PROD.LIMPIEZA INTERIOR",
          "PROD.RECEPCION SONGA 2 VA",
          "PRODUCCION BRINE",
          "PRODUCCION DPTO",
          "PRODUCCION OBRERO",
          "PRODUCCIÓN SONGA 2 VA",
          "PROYECTOS",
          "RECURSOS HUMANOS",
          "REFRIGERACION",
          "RETRACTILADO",
          "SEGURIDAD INDUSTRIAL Y SALUD",
          "SISTEMA DE G. Y CALIDAD Y LIQU",
          "SOLDADOR",
          "TRANSFERENCIA S2"
        ],
        "Catalogo": "SUB_CENTRO"
      },
      {
        "Orden": 14,
        "Etiqueta": "En qué turno ocurrió el evento",
        "Tipo": "LISTA_DESPLEGABLE",
        "Categoria": "DATOS_COLABORADOR",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [
          "Día",
          "Noche"
        ],
        "Catalogo": "TURNO"
      },
      {
        "Orden": 15,
        "Etiqueta": "Derivación",
        "Tipo": "LISTA_DESPLEGABLE",
        "Categoria": "DERIVACION_EVENTO",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [
          "Nómina y Compensaciones",
          "Departamento Médico / Salud Ocupacional",
          "Bienestar Laboral / Trabajo Social",
          "Seguridad Industrial",
          "Talento Humano",
          "Jefatura o área operativa",
          "Derivación a varias áreas",
          "No requiere derivación"
        ],
        "Catalogo": "DESTINO_DERIVACION",
        "ValorPredeterminado": ""
      },
      {
        "Orden": 16,
        "Etiqueta": "Estado de la derivación",
        "Tipo": "LISTA_DESPLEGABLE",
        "Categoria": "DERIVACION_EVENTO",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [
          "Pendiente de derivación",
          "Derivado",
          "Recibido por el área",
          "En atención",
          "Pendiente de información",
          "Atendido",
          "Devuelto para ampliación",
          "Cerrado"
        ],
        "Catalogo": "ESTADO_DERIVACION",
        "DependeDe": "Derivación",
        "OperadorDependencia": "IN",
        "ValoresDependencia": [
          "Nómina y Compensaciones",
          "Departamento Médico / Salud Ocupacional",
          "Bienestar Laboral / Trabajo Social",
          "Seguridad Industrial",
          "Talento Humano",
          "Jefatura o área operativa",
          "Derivación a varias áreas"
        ]
      },
      {
        "Orden": 17,
        "Etiqueta": "Tipo de Evento",
        "Tipo": "LISTA_DESPLEGABLE",
        "Categoria": "DERIVACION_EVENTO",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [
          "Accidente",
          "Incidente",
          "Ninguno"
        ],
        "Catalogo": "TIPO_EVENTO"
      },
      {
        "Orden": 18,
        "Etiqueta": "Condición laboral",
        "Tipo": "LISTA_DESPLEGABLE",
        "Categoria": "RESTRICCION_RIESGO",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [
          "Con restricciones laborales",
          "Personal reubicado",
          "Con restricciones y reubicación",
          "Pendiente de valoración o confirmación"
        ],
        "Catalogo": "CONDICION_LABORAL"
      },
      {
        "Orden": 19,
        "Etiqueta": "Fecha de Inicio de Restricción",
        "Tipo": "FECHA",
        "Categoria": "RESTRICCION_RIESGO",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": []
      },
      {
        "Orden": 20,
        "Etiqueta": "Fecha de culminación de Restricción",
        "Tipo": "FECHA",
        "Categoria": "RESTRICCION_RIESGO",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": []
      },
      {
        "Orden": 21,
        "Etiqueta": "Se reporto a Riesgo de Trabajo",
        "Tipo": "SI_NO",
        "Categoria": "RESTRICCION_RIESGO",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [],
        "ValorPredeterminado": "false"
      },
      {
        "Orden": 22,
        "Etiqueta": "A qué área se lo designa",
        "Tipo": "TEXTO_CORTO",
        "Categoria": "RESTRICCION_RIESGO",
        "Obligatoria": false,
        "Visible": true,
        "SoloLectura": false,
        "Opciones": [],
        "TextoAyuda": "Ingrese el área de designación.",
        "LongitudMaxima": 250
      }
    ]
  };
}

