"""Accidentes e importaciones XLSX persistentes."""
from alembic import op
import sqlalchemy as sa
revision = "0018_accidentes"
down_revision = "0017_registros_operativos_ausentismos"
branch_labels = None
depends_on = None
def _meta():
    return [sa.Column(name, typ, nullable=nullable) for name, typ, nullable in [("activo", sa.Boolean(create_constraint=True), False), ("eliminado", sa.Boolean(create_constraint=True), False), ("fecha_creacion", sa.String(), True), ("creado_por", sa.String(), True), ("fecha_actualizacion", sa.String(), True), ("actualizado_por", sa.String(), True), ("fecha_eliminacion", sa.String(), True), ("usuario_eliminacion", sa.String(), True), ("motivo_eliminacion", sa.String(), True), ("version", sa.Integer(), False), ("archivo_fuente", sa.String(), True), ("hoja_fuente", sa.String(), True), ("registro_fuente", sa.String(), True), ("fecha_importacion", sa.String(), True), ("usuario_importacion", sa.String(), True)]]
def upgrade():
    op.create_table("lotes_importacion_accidente", sa.Column("id_lote", sa.String(), primary_key=True), sa.Column("nombre_archivo", sa.String(), nullable=False), sa.Column("contenido_archivo", sa.LargeBinary(), nullable=False), sa.Column("usuario_id", sa.String(), sa.ForeignKey("usuarios.id_usuario"), nullable=False), sa.Column("estado", sa.String(), nullable=False), sa.Column("total_filas", sa.Integer(), nullable=False), sa.Column("filas_validas", sa.Integer(), nullable=False), sa.Column("filas_con_error", sa.Integer(), nullable=False), sa.Column("filas_duplicadas", sa.Integer(), nullable=False), sa.Column("filas_importadas", sa.Integer(), nullable=False), *_meta(), sa.CheckConstraint("version >= 1", name="version_positive")); op.create_index("ix_lotes_importacion_accidente_usuario_id", "lotes_importacion_accidente", ["usuario_id"])
    op.create_table("accidentes", sa.Column("id_accidente", sa.String(), primary_key=True), sa.Column("persona_id", sa.String(), sa.ForeignKey("personas.id_persona"), nullable=False), sa.Column("lote_id", sa.String(), sa.ForeignKey("lotes_importacion_accidente.id_lote"), nullable=True), sa.Column("fecha_accidente", sa.String(), nullable=False), sa.Column("clasificacion", sa.String(), nullable=False), sa.Column("estado", sa.String(), nullable=False), sa.Column("descripcion", sa.String(), nullable=False), sa.Column("observacion", sa.String(), nullable=True), *_meta(), sa.UniqueConstraint("persona_id", "fecha_accidente", "clasificacion", name="uq_accidentes_persona_fecha_clasificacion"), sa.CheckConstraint("version >= 1", name="version_positive")); op.create_index("ix_accidentes_persona_id", "accidentes", ["persona_id"]); op.create_index("ix_accidentes_lote_id", "accidentes", ["lote_id"])
    op.create_table("errores_importacion_accidente", sa.Column("id_error", sa.String(), primary_key=True), sa.Column("lote_id", sa.String(), sa.ForeignKey("lotes_importacion_accidente.id_lote"), nullable=False), sa.Column("numero_fila", sa.Integer(), nullable=False), sa.Column("codigo", sa.String(), nullable=False), sa.Column("mensaje", sa.String(), nullable=False), sa.Column("datos_fila", sa.String(), nullable=True), *_meta(), sa.CheckConstraint("version >= 1", name="version_positive")); op.create_index("ix_errores_importacion_accidente_lote_id", "errores_importacion_accidente", ["lote_id"]); op.create_index("ix_errores_importacion_accidente_lote_fila", "errores_importacion_accidente", ["lote_id", "numero_fila"])
def downgrade():
    op.drop_table("errores_importacion_accidente"); op.drop_table("accidentes"); op.drop_table("lotes_importacion_accidente")
