import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it, vi, beforeEach } from 'vitest';
import { FeedbackProvider } from '../../components/FeedbackProvider';
import { AusentismosPage } from './AusentismosPage';
import * as api from '../../api/importacionesAusentismos';
import { HttpError } from '../../api/client';

vi.mock('../../api/importacionesAusentismos');
const lote = { id_lote: 'lote-1', nombre_archivo: 'ausencias.xlsx', usuario_id: 'admin', estado: 'ANALIZADO' as const, total_filas: 2, filas_validas: 2, filas_con_error: 0, filas_duplicadas: 0, filas_importadas: 0, fecha_creacion: '2026-09-15T10:00:00Z', fecha_actualizacion: null, version: 1 };
const renderPage = () => render(<FeedbackProvider><AusentismosPage /></FeedbackProvider>);
beforeEach(() => { vi.clearAllMocks(); vi.mocked(api.listarLotesAusentismos).mockResolvedValue({ items: [], total: 0, limite: 25, offset: 0 }); vi.mocked(api.listarErroresLoteAusentismos).mockResolvedValue({ items: [], total: 0, limite: 25, offset: 0 }); });

describe('AusentismosPage', () => {
  it('renderiza importar XLSX, selección y reemplazo', async () => { renderPage(); expect(screen.getByRole('tab', { name: 'Importar XLSX' })).toBeInTheDocument(); const input = screen.getByLabelText('Seleccionar archivo XLSX'); await userEvent.upload(input, new File(['xlsx'], 'carga.xlsx', { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })); expect(screen.getByText(/carga.xlsx/)).toBeInTheDocument(); await userEvent.click(screen.getByText('Reemplazar')); expect(screen.queryByText(/Archivo seleccionado/)).not.toBeInTheDocument(); });
  it('analiza y muestra resumen de lote válido con confirmación', async () => { vi.mocked(api.analizarAusentismos).mockResolvedValue({ lote, puede_confirmarse: true, previsualizacion: [] }); renderPage(); await userEvent.upload(screen.getByLabelText('Seleccionar archivo XLSX'), new File(['x'], 'carga.xlsx')); await userEvent.click(screen.getByText('Analizar archivo')); expect(await screen.findByText(/Estado: Listo para confirmar/)).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Confirmar importación' })).toBeEnabled(); });
  it('muestra errores, datos seguros y bloquea confirmación', async () => { const errorLote = { ...lote, filas_validas: 0, filas_con_error: 1 }; vi.mocked(api.analizarAusentismos).mockResolvedValue({ lote: errorLote, puede_confirmarse: false, previsualizacion: [] }); vi.mocked(api.listarErroresLoteAusentismos).mockResolvedValue({ items: [{ id_error: 'e1', numero_fila: 4, codigo: 'VALIDACION', mensaje: 'Fecha inválida', datos_fila: '{"cedula":"******5678","motivo":"Consulta"}' }], total: 1, limite: 25, offset: 0 }); renderPage(); await userEvent.upload(screen.getByLabelText('Seleccionar archivo XLSX'), new File(['x'], 'carga.xlsx')); await userEvent.click(screen.getByText('Analizar archivo')); expect(await screen.findByText('Fecha inválida')).toBeInTheDocument(); expect(screen.getByText(/\*\*\*\*\*\*5678/)).toBeInTheDocument(); expect(screen.queryByText('Confirmar importación')).not.toBeInTheDocument(); });
  it('confirma por lote mediante el modal y evita doble submit', async () => { vi.mocked(api.analizarAusentismos).mockResolvedValue({ lote, puede_confirmarse: true, previsualizacion: [] }); vi.mocked(api.confirmarLoteAusentismos).mockImplementation(() => new Promise(() => {})); renderPage(); await userEvent.upload(screen.getByLabelText('Seleccionar archivo XLSX'), new File(['x'], 'carga.xlsx')); await userEvent.click(screen.getByText('Analizar archivo')); await screen.findByText(/Estado: Listo para confirmar/); await userEvent.click(screen.getByRole('button', { name: 'Confirmar importación' })); const dialog = screen.getByRole('dialog'); expect(within(dialog).getByText('Esta acción registrará los Ausentismos válidos del lote.')).toBeInTheDocument(); await userEvent.click(within(dialog).getByRole('button', { name: 'Confirmar importación' })); await waitFor(() => expect(api.confirmarLoteAusentismos).toHaveBeenCalledWith('lote-1')); expect(screen.getByText('Confirmando…')).toBeDisabled(); });
  it('informa confirmación exitosa y error de confirmación', async () => { vi.mocked(api.analizarAusentismos).mockResolvedValue({ lote, puede_confirmarse: true, previsualizacion: [] }); vi.mocked(api.confirmarLoteAusentismos).mockResolvedValue({ ...lote, estado: 'CONFIRMADO', filas_importadas: 2 }); renderPage(); await userEvent.upload(screen.getByLabelText('Seleccionar archivo XLSX'), new File(['x'], 'carga.xlsx')); await userEvent.click(screen.getByText('Analizar archivo')); await screen.findByText(/Estado: Listo para confirmar/); await userEvent.click(screen.getByRole('button', { name: 'Confirmar importación' })); await userEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Confirmar importación' })); expect(await screen.findByText(/Estado: Confirmado/)).toBeInTheDocument(); });
  it('muestra historial, detalle, vacío y paginación', async () => { vi.mocked(api.listarLotesAusentismos).mockResolvedValue({ items: [lote], total: 26, limite: 25, offset: 0 }); vi.mocked(api.obtenerLoteAusentismos).mockResolvedValue(lote); renderPage(); await userEvent.click(screen.getByText('Historial de cargas')); expect(await screen.findByText('ausencias.xlsx')).toBeInTheDocument(); await userEvent.click(screen.getByText('Siguiente')); await waitFor(() => expect(api.listarLotesAusentismos).toHaveBeenLastCalledWith(expect.objectContaining({}))); await userEvent.click(screen.getByText('Ver detalle')); expect(await screen.findByText('Detalle del lote')).toBeInTheDocument(); });
  it('muestra errores 401, 403 y de red devueltos por API', async () => { vi.mocked(api.listarLotesAusentismos).mockRejectedValueOnce(new HttpError(401, { ok: false, code: 'SESSION_REQUIRED', message: 'Inicie sesión.', correlationId: '' })); vi.mocked(api.analizarAusentismos).mockRejectedValue(new HttpError(403, { ok: false, code: 'FORBIDDEN', message: 'Sin permiso.', correlationId: '' })); renderPage(); expect(await screen.findByText('Inicie sesión.')).toBeInTheDocument(); await userEvent.upload(screen.getByLabelText('Seleccionar archivo XLSX'), new File(['x'], 'carga.xlsx')); await userEvent.click(screen.getByText('Analizar archivo')); expect(await screen.findByText('Sin permiso.')).toBeInTheDocument(); });
});
