import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it, vi, beforeEach } from 'vitest';
import { FeedbackProvider } from '../../components/FeedbackProvider';
import { AusentismosPage } from './AusentismosPage';
import * as api from '../../api/importacionesAusentismos';
import * as recordsApi from '../../api/ausentismos';
import { HttpError } from '../../api/client';

vi.mock('../../api/importacionesAusentismos');
vi.mock('../../api/ausentismos');
const lote = { id_lote: 'lote-1', nombre_archivo: 'ausencias.xlsx', usuario_id: 'admin', estado: 'ANALIZADO' as const, total_filas: 2, filas_validas: 2, filas_con_error: 0, filas_duplicadas: 0, filas_importadas: 0, fecha_creacion: '2026-09-15T10:00:00Z', fecha_actualizacion: null, version: 1 };
const record = { id_ausentismo: 'aus-1', persona_id: 'persona-1', persona: 'Ana Pérez', cedula: '0012345678', area: 'Operaciones', fecha_inicio: '2026-09-10', fecha_fin: '2026-09-12', tipo_ausentismo: 'MEDICO', motivo: 'Certificado', observacion: 'Revisado', fecha_registro: '2026-09-15T10:00:00Z', registrado_por_id: 'admin', registrado_por: 'Administradora', origen: 'IMPORTACION_XLSX', lote_id: 'lote-1', lote_nombre_archivo: 'ausencias.xlsx' };
const renderPage = () => render(<FeedbackProvider><AusentismosPage /></FeedbackProvider>);
beforeEach(() => { vi.clearAllMocks(); vi.mocked(api.listarLotesAusentismos).mockResolvedValue({ items: [], total: 0, limite: 25, offset: 0 }); vi.mocked(api.listarErroresLoteAusentismos).mockResolvedValue({ items: [], total: 0, limite: 25, offset: 0 }); vi.mocked(recordsApi.listarAusentismos).mockResolvedValue({ items: [], total: 0, limite: 25, offset: 0 }); });

describe('AusentismosPage', () => {
  it('renderiza importar XLSX, selección y reemplazo', async () => { renderPage(); expect(screen.getByRole('tab', { name: 'Importar XLSX' })).toBeInTheDocument(); const input = screen.getByLabelText('Seleccionar archivo XLSX'); await userEvent.upload(input, new File(['xlsx'], 'carga.xlsx', { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })); expect(screen.getByText(/carga.xlsx/)).toBeInTheDocument(); await userEvent.click(screen.getByText('Reemplazar')); expect(screen.queryByText(/Archivo seleccionado/)).not.toBeInTheDocument(); });
  it('analiza y muestra resumen de lote válido con confirmación', async () => { vi.mocked(api.analizarAusentismos).mockResolvedValue({ lote, puede_confirmarse: true, previsualizacion: [] }); renderPage(); await userEvent.upload(screen.getByLabelText('Seleccionar archivo XLSX'), new File(['x'], 'carga.xlsx')); await userEvent.click(screen.getByText('Analizar archivo')); expect(await screen.findByText(/Estado: Listo para confirmar/)).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Confirmar importación' })).toBeEnabled(); });
  it('muestra errores, datos seguros y bloquea confirmación', async () => { const errorLote = { ...lote, filas_validas: 0, filas_con_error: 1 }; vi.mocked(api.analizarAusentismos).mockResolvedValue({ lote: errorLote, puede_confirmarse: false, previsualizacion: [] }); vi.mocked(api.listarErroresLoteAusentismos).mockResolvedValue({ items: [{ id_error: 'e1', numero_fila: 4, codigo: 'VALIDACION', mensaje: 'Fecha inválida', datos_fila: '{"cedula":"******5678","motivo":"Consulta"}' }], total: 1, limite: 25, offset: 0 }); renderPage(); await userEvent.upload(screen.getByLabelText('Seleccionar archivo XLSX'), new File(['x'], 'carga.xlsx')); await userEvent.click(screen.getByText('Analizar archivo')); expect(await screen.findByText('Fecha inválida')).toBeInTheDocument(); expect(screen.getByText(/\*\*\*\*\*\*5678/)).toBeInTheDocument(); expect(screen.queryByText('Confirmar importación')).not.toBeInTheDocument(); });
  it('confirma por lote mediante el modal y evita doble submit', async () => { vi.mocked(api.analizarAusentismos).mockResolvedValue({ lote, puede_confirmarse: true, previsualizacion: [] }); vi.mocked(api.confirmarLoteAusentismos).mockImplementation(() => new Promise(() => {})); renderPage(); await userEvent.upload(screen.getByLabelText('Seleccionar archivo XLSX'), new File(['x'], 'carga.xlsx')); await userEvent.click(screen.getByText('Analizar archivo')); await screen.findByText(/Estado: Listo para confirmar/); await userEvent.click(screen.getByRole('button', { name: 'Confirmar importación' })); const dialog = screen.getByRole('dialog'); expect(within(dialog).getByText('Esta acción registrará los Ausentismos válidos del lote.')).toBeInTheDocument(); await userEvent.click(within(dialog).getByRole('button', { name: 'Confirmar importación' })); await waitFor(() => expect(api.confirmarLoteAusentismos).toHaveBeenCalledWith('lote-1')); expect(screen.getByText('Confirmando…')).toBeDisabled(); });
  it('informa confirmación exitosa y error de confirmación', async () => { vi.mocked(api.analizarAusentismos).mockResolvedValue({ lote, puede_confirmarse: true, previsualizacion: [] }); vi.mocked(api.confirmarLoteAusentismos).mockResolvedValue({ ...lote, estado: 'CONFIRMADO', filas_importadas: 2 }); renderPage(); await userEvent.upload(screen.getByLabelText('Seleccionar archivo XLSX'), new File(['x'], 'carga.xlsx')); await userEvent.click(screen.getByText('Analizar archivo')); await screen.findByText(/Estado: Listo para confirmar/); await userEvent.click(screen.getByRole('button', { name: 'Confirmar importación' })); await userEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Confirmar importación' })); expect(await screen.findByText(/Estado: Confirmado/)).toBeInTheDocument(); });
  it('muestra historial, detalle, vacío y paginación', async () => { vi.mocked(api.listarLotesAusentismos).mockResolvedValue({ items: [lote], total: 26, limite: 25, offset: 0 }); vi.mocked(api.obtenerLoteAusentismos).mockResolvedValue(lote); renderPage(); await userEvent.click(screen.getByText('Historial de cargas')); expect(await screen.findByText('ausencias.xlsx')).toBeInTheDocument(); await userEvent.click(screen.getByText('Siguiente')); await waitFor(() => expect(api.listarLotesAusentismos).toHaveBeenLastCalledWith(expect.objectContaining({}))); await userEvent.click(screen.getByText('Ver detalle')); expect(await screen.findByText('Detalle del lote')).toBeInTheDocument(); });
  it('muestra errores 401, 403 y de red devueltos por API', async () => { vi.mocked(api.listarLotesAusentismos).mockRejectedValueOnce(new HttpError(401, { ok: false, code: 'SESSION_REQUIRED', message: 'Inicie sesión.', correlationId: '' })); vi.mocked(api.analizarAusentismos).mockRejectedValue(new HttpError(403, { ok: false, code: 'FORBIDDEN', message: 'Sin permiso.', correlationId: '' })); renderPage(); expect(await screen.findByText('Inicie sesión.')).toBeInTheDocument(); await userEvent.upload(screen.getByLabelText('Seleccionar archivo XLSX'), new File(['x'], 'carga.xlsx')); await userEvent.click(screen.getByText('Analizar archivo')); expect(await screen.findByText('Sin permiso.')).toBeInTheDocument(); });
  it('muestra la tabla individual con Persona, cédula textual, área, autor y origen reales', async () => { vi.mocked(recordsApi.listarAusentismos).mockResolvedValue({ items: [record, { ...record, id_ausentismo: 'historico', registrado_por: null, origen: null }], total: 2, limite: 25, offset: 0 }); renderPage(); await userEvent.click(screen.getByRole('tab', { name: 'Registros' })); expect((await screen.findAllByText('Ana Pérez')).length).toBe(2); expect(screen.getAllByText('0012345678')[0]).toBeInTheDocument(); expect(screen.getAllByText('Operaciones')[0]).toBeInTheDocument(); expect(screen.getByText('Administradora')).toBeInTheDocument(); expect(screen.getByText('IMPORTACION_XLSX')).toBeInTheDocument(); expect(screen.getAllByText('Sin información').length).toBeGreaterThanOrEqual(2); });
  it('aplica filtros server-side, los combina, limpia y reinicia la paginación', async () => { vi.mocked(recordsApi.listarAusentismos).mockResolvedValue({ items: [record], total: 26, limite: 25, offset: 0 }); renderPage(); await userEvent.click(screen.getByRole('tab', { name: 'Registros' })); await screen.findByText('Ana Pérez'); await userEvent.type(screen.getByLabelText('Filtrar por nombre'), 'Ana'); await userEvent.type(screen.getByLabelText('Filtrar por cédula'), '0012345678'); await userEvent.type(screen.getByLabelText('Filtrar por área'), 'Operaciones'); await userEvent.type(screen.getByLabelText('Filtrar por tipo de ausentismo'), 'MEDICO'); await userEvent.selectOptions(screen.getByLabelText('Filtrar por origen'), 'IMPORTACION_XLSX'); await userEvent.click(screen.getByRole('button', { name: 'Aplicar filtros' })); await waitFor(() => expect(vi.mocked(recordsApi.listarAusentismos).mock.calls.at(-1)?.[0].get('nombre')).toBe('Ana')); const applied = vi.mocked(recordsApi.listarAusentismos).mock.calls.at(-1)?.[0]; expect(applied?.get('cedula')).toBe('0012345678'); expect(applied?.get('area')).toBe('Operaciones'); expect(applied?.get('tipo_ausentismo')).toBe('MEDICO'); expect(applied?.get('origen')).toBe('IMPORTACION_XLSX'); await userEvent.click(screen.getByRole('button', { name: 'Siguiente' })); await waitFor(() => expect(vi.mocked(recordsApi.listarAusentismos).mock.calls.at(-1)?.[0].get('offset')).toBe('25')); expect(vi.mocked(recordsApi.listarAusentismos).mock.calls.at(-1)?.[0].get('nombre')).toBe('Ana'); await userEvent.click(screen.getByRole('button', { name: 'Limpiar filtros' })); await waitFor(() => expect(vi.mocked(recordsApi.listarAusentismos).mock.calls.at(-1)?.[0].get('offset')).toBe('0')); expect(vi.mocked(recordsApi.listarAusentismos).mock.calls.at(-1)?.[0].get('nombre')).toBeNull(); });
  it('muestra rango, total y conserva filtros al navegar', async () => { vi.mocked(recordsApi.listarAusentismos).mockResolvedValue({ items: [record], total: 26, limite: 25, offset: 0 }); renderPage(); await userEvent.click(screen.getByRole('tab', { name: 'Registros' })); expect(await screen.findByText('Mostrando 1-1 de 26')).toBeInTheDocument(); await userEvent.type(screen.getByLabelText('Filtrar por lote'), 'lote-1'); await userEvent.click(screen.getByText('Aplicar filtros')); await userEvent.click(screen.getByText('Siguiente')); await waitFor(() => expect(vi.mocked(recordsApi.listarAusentismos).mock.calls.at(-1)?.[0].get('lote_id')).toBe('lote-1')); });
  it('abre detalle individual con observación, lote y metadatos secundarios', async () => { vi.mocked(recordsApi.listarAusentismos).mockResolvedValue({ items: [record], total: 1, limite: 25, offset: 0 }); vi.mocked(recordsApi.obtenerAusentismo).mockResolvedValue(record); renderPage(); await userEvent.click(screen.getByRole('tab', { name: 'Registros' })); await screen.findByText('Ana Pérez'); await userEvent.click(screen.getByRole('button', { name: 'Ver detalle' })); expect(await screen.findByRole('dialog')).toBeInTheDocument(); expect(screen.getByText('Revisado')).toBeInTheDocument(); expect(screen.getByText(/ausencias.xlsx/)).toBeInTheDocument(); expect(recordsApi.obtenerAusentismo).toHaveBeenCalledWith('aus-1'); });
  it('distingue loading, vacío y errores 401, 403 y API en Registros', async () => { let resolve!: (value: { items: typeof record[]; total: number; limite: number; offset: number }) => void; vi.mocked(recordsApi.listarAusentismos).mockImplementationOnce(() => new Promise((done) => { resolve = done; })); renderPage(); await userEvent.click(screen.getByRole('tab', { name: 'Registros' })); expect(screen.getByText('Cargando registros…')).toBeInTheDocument(); resolve({ items: [], total: 0, limite: 25, offset: 0 }); expect(await screen.findByText(/No existen registros de Ausentismos/)).toBeInTheDocument(); vi.mocked(recordsApi.listarAusentismos).mockRejectedValueOnce(new HttpError(401, { ok: false, code: 'SESSION_REQUIRED', message: 'Inicie sesión.', correlationId: '' })); await userEvent.click(screen.getByText('Aplicar filtros')); expect(await screen.findByText('Inicie sesión.')).toBeInTheDocument(); vi.mocked(recordsApi.listarAusentismos).mockRejectedValueOnce(new HttpError(403, { ok: false, code: 'FORBIDDEN', message: 'Sin permiso.', correlationId: '' })); await userEvent.click(screen.getByText('Aplicar filtros')); expect(await screen.findByText('Sin permiso.')).toBeInTheDocument(); });
});
